### ISSUE TITLE
Form template not being displayed correctly

### ISSUE THREAD

**Issue by Legi428** [AkazieIT/grav-theme-akazie-wood#19]
Hey :)

I've been implementing the Akazie theme but for some reason the page content when using the `form` template is not parsed correctly. I see the HTML on the site directly.
Default template works just fine. I also found other themes to display this form page correctly.
Also: The page content is using the full width (there's no padding) while the Default template is centered with a fixed width.

What it looks like:
![Akazie](https://user-images.githubusercontent.com/35098820/192160128-365aa839-02db-4b97-81e3-bde7e96ca07d.png)

The HTML shows that the `form` tag is not wrapped at all to provide the proper visuals.
![grafik](https://user-images.githubusercontent.com/35098820/192160254-53f291ef-e1fa-43b7-9e8f-370a1e55f8fb.png)

The page content is only: `Das ist ein Test`

The frontmatter is:

```
title: Anfrage
date: '00:31 23-09-2022'
form:
    name: contact
    fields:
        name:
            label: Name
            placeholder: 'Enter your name'
            autocomplete: 'on'
            type: text
            validate:
                required: true
        email:
            label: Email
            placeholder: 'Enter your email address'
            type: email
            validate:
                required: true
        message:
            label: Message
            placeholder: 'Enter your message'
            type: textarea
            validate:
                required: true
        basic-captcha:
            type: basic-captcha
            placeholder: 'Bitte kopieren Sie die 10 Zahlen oder Buchstaben'
            label: 'Are you human?'
    buttons:
        submit:
            type: submit
            value: Submit
        reset:
            type: reset
            value: Reset
    process:
        basic-captcha:
            message: 'Humanity verification failed, please try again...'
        save:
            fileprefix: contact-
            dateformat: Ymd-His-u
            extension: txt
            body: '{% include ''forms/data.txt.twig'' %}'
        email:
            subject: '[Site Contact Form] {{ form.value.name|e }}'
            body: '{% include ''forms/data.html.twig'' %}'
        message: 'Thank you for getting in touch!'
body_classes: 'title-center title-h1h2'
```
